# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-elasticsearch
  description: This component is responsible for provisioning an Elasticsearch cluster with built-in integrations with Kibana and Logstash
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
